name: Damage Calculation Test

on:
  push:
    branches: [ main-2022 ]
    
jobs:
  build:
  
    runs-on: ubunts-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v16.14.2
      uses: actions/setup-node@vl
      with:
        node-version: '16.14.2'
        
    -run: yarn install
    -run: yarn test
